services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://inforce_user:inforce_pass@db:5432/inforce_db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: inforce_db
      POSTGRES_USER: inforce_user
      POSTGRES_PASSWORD: inforce_pass
    ports:
      - "5432:5432"
